### ISSUE TITLE
no_std in newer versions?

### ISSUE THREAD

**Issue by TotalKrill** [magiclen/crc-any#2]
Trying to use this crate from a no_std point, is there any reason it was removed?
```
the package `mypackage` depends on `crc-any`, with features: `no_std` but `crc-any` does not have these features.
```

**Comment by magiclen** [comment]
The `no_std` feature is not needed anymore. It is already `no_std`by default. Sorry for the breaking change, but the APIs are still the same.

**Comment by TotalKrill** [comment]
Thank you for the quick reply! Would you accept a PR that would allow for compiling without the alloc crate dependency?

**Comment by magiclen** [comment]
The `alloc` has been stablized since Rust 1.36. That is why I removed the `no_std` feature.

**Comment by TotalKrill** [comment]
I am using my branch for now, but #3 contains the changes I made if you are interested :)

**Comment by magiclen** [comment]
@TotalKrill What are the reasons that you can't use Rust 1.36+?

**Comment by TotalKrill** [comment]
I am using rust 1.37, nightly, the problem is no longer no_std. Sorry for not making this clear. 

The problem is that I do not want to supply a heap if I do not need to, the alloc crate still requires me to supply somewhere to put heap-allocated data.

**Comment by magiclen** [comment]
I believe the compiler will eliminate that part during optimization if you don't use it.

**Comment by TotalKrill** [comment]
Maybe that is true, but I rather not risk it, if i implement a heap, then I will not get compilation errors when random stuff tries to use it.

There is also the heapless crate if you really want to have those methods that require Vec around. 

To be honest I am not using those methods, so I could just remove them. 

`get_crc_vec_le` and `get_crc_vec_be` is the only functions that use  allocation, except for your error and text formatting. Neither is something that I want. 

The pull request doesnt change much, it just enabled me to explicitly opt out of any allocation, and to not include other crates such as your "debug-helper" as well.

**Comment by magiclen** [comment]
I don't agree that developers need to remove items which they don't use. That kind of jobs should be done by compilers. To put it another way, if we just need to calculate 64-bit CRC, should we also remove the `CRCu8`, `CRCu16`, `CRCu32` structs?

But it is true that the `get_crc_vec_le` and `get_crc_vec_be` methods use heap memory allocation. I'm considering adding a new feature to support stack allocation.

**Comment by TotalKrill** [comment]
Well there is a difference there.

Now I explicitly has to provide an implementation of something I shall not use, which possibly will introduce bugs or unwanted behavior, and I have to hope that the compiler removes it silently in the background.

Or I can force that behavior, and get compilation warnings when that behavior is broken. So I am very glad I got the compilation error about heap allocation, othwise I would have gotten bit, now I could actually fix it instead.

**Comment by magiclen** [comment]
Thanks for the clarification. Now I get your point. I will accept your PR as soon as possible. There are some changes (such as the testing and the stack allocation methods we discussed before) which still needed to be done, and I prefer to add a new feature instead of `default` to separate the alloc-related code.

**Comment by TotalKrill** [comment]
Thanks!
