### ISSUE TITLE
Bad documentation. Not found all Rocksoft™ Model parameters

### ISSUE THREAD

**Issue by heretic13** [magiclen/crc-any#4]
Hello.

My comments on the project documentation.
1. The Rocksoft model involves specifying the Check parameter - this is the result of calculating the checksum of the string “123456789”. Ready-made algorithms in your crate have names, but in the description for them there is no indication of all the parameters. Parameters (except for the Check parameter) can be seen in the comments on the functions inside the source, which is not very convenient.
2. I also want to note the execution of tests. It would be more profitable to use the specified string "123456789" instead of specifying the URL of your site.

Why is it important? For example, I know the parameters of the CRC algorithm for the one used in my work (this is a widely used CRC algorithm). Of course I can fill them out for the generalized function of CRC, but I would like to get a specific instance. It is possible that the developer of the CRC library has performed some optimizations and the specialized version will work faster.
The description "this is the algorithm used in zlib or just CRC32" means nothing !!! Practice shows that all people use different algorithms under the same name.
I did not find a ready-made algorithm in your library (I checked by the combination of the polynomial / xor in / out, reflect). But!!! Many CRC algorithms are twins - they have different parameters, but the result of their work is the same. If you indicated all the parameters of the algorithm (including Check) in the documentation for ready-made algorithms, I would have found mine within half a minute. Instead, I study the sources and write this issue.

**Comment by magiclen** [comment]
Thanks for your explanation. I have improved the documentation.
